export const PRODUCTS_ADMIN = '/admin/products'
export const ORDERS_ADMIN = '/admin/orders'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/register'
export const HOME_ROUTE = '/'
export const ABOUT_ROUTE = '/about'
export const CATALOG_ROUTE = '/catalog'
export const CART_ROUTE = '/cart'